name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:        # Allows manual triggering if needed

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP request to Render
        run: curl -s https://your-app-name.onrender.com > /dev/null
