name: Keep Render Alive

on:
  schedule:
    - cron: "*/7 * * * *"  # Every 7 minutes
  workflow_dispatch:        # Optional: manual trigger

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl -s https://double-bluff.onrender.com > /dev/null
